server:
  port: 8080
  servlet:
    context-path: /item
spring:
  datasource:
    name: testname
    url: jdbc:mysql://127.0.0.1/item?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jmx:
    enabled: false
  servlet:
    multipart:
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.item.entity
logging:
  pattern:
    console: '%d -%msg%n'
  level:
    root: error
    com.luti.mapper : info


